In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("sales_data_25000.csv")

# Understanding data

In [3]:
print("Shape : ",df.shape)
print("Column names :",df.columns)

Shape :  (25075, 13)
Column names : Index(['Order ID', 'Order Date', 'Customer ID', 'Customer Type', 'Product',
       'Category', 'Region', 'City', 'Quantity', 'Price Each', 'Discount',
       'Sales', 'Payment Mode'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25075 entries, 0 to 25074
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       25075 non-null  object
 1   Order Date     25075 non-null  object
 2   Customer ID    25075 non-null  object
 3   Customer Type  25040 non-null  object
 4   Product        25075 non-null  object
 5   Category       25075 non-null  object
 6   Region         25075 non-null  object
 7   City           25040 non-null  object
 8   Quantity       25075 non-null  int64
 9   Price Each     25075 non-null  float64
 10  Discount       25075 non-null  float64
 11  Sales          25075 non-null  float64
 12  Payment Mode   25045 non-null  object
dtypes: float64(3), int64(1), object(9)
memory usage: 2.5+ MB

In [5]:
df.head(10)

,Order ID,Order Date,Customer ID,Customer Type,Product,Category,Region,City,Quantity,Price Each,Discount,Sales,Payment Mode
0,ORD112908,2024-10-16,CUST11433,New,Bookshelf,Furniture,North,Delhi,6,6639.25,0.10,35851.95,Net Banking
1,ORD114592,2025-08-15,CUST11178,Regular,Pen Set,Stationery,West,Aurangabad,2,193.78,0.03,375.93,Debit Card
2,ORD111761,2025-09-28,CUST10146,Regular,Coffee Maker,Home Appliances,West,Pune,5,4122.21,0.05,19580.50,UPI
3,ORD114241,2025-09-26,CUST11112,Regular,Pen Set,Stationery,South,Chennai,2,169.92,0.03,329.64,UPI
4,ORD108748,2024-03-09,CUST11484,Premium,Air Fryer,Home Appliances,North,Delhi,5,6349.53,0.10,28572.88,Credit Card
5,ORD112116,2025-10-07,CUST11540,Regular,Laptop,Electronics,North,Delhi,6,57899.59,0.08,319605.74,UPI
6,ORD101427,2025-01-25,CUST10382,Regular,Jeans,Fashion,East,Bhubaneswar,1,1863.47,0.03,1807.57,Credit Card
7,ORD104203,2025-12-28,CUST11806,Regular,Desk,Furniture,Central,Nagpur,2,12112.40,0.05,23013.56,Debit Card
8,ORD124493,2024-02-20,CUST10161,Premium,Keyboard,Electronics,East,Patna,3,1339.69,0.15,3416.21,Net Banking
9,ORD114790,2024-08-11,CUST10676,Regular,Monitor,Electronics,South,Kochi,3,11154.12,0.03,32458.49,UPI

In [6]:
df.tail(10)

,Order ID,Order Date,Customer ID,Customer Type,Product,Category,Region,City,Quantity,Price Each,Discount,Sales,Payment Mode
25065,ORD116850,2025-12-01,CUST10473,Premium,Coffee Maker,Home Appliances,North,Delhi,3,4064.00,0.10,10972.80,Credit Card
25066,ORD106265,2025-12-05,CUST10589,Regular,Mouse,Electronics,West,Aurangabad,3,689.46,0.03,2006.33,Net Banking
25067,ORD122118,2024-05-30,CUST10576,Premium,Bookshelf,Furniture,South,Hyderabad,7,6354.59,0.12,39144.27,Debit Card
25068,ORD111284,2025-11-24,CUST12109,Premium,Blender,Home Appliances,South,Kochi,4,2792.39,0.10,10052.60,UPI
25069,ORD111964,2024-01-26,CUST11571,New,Office Chair,Furniture,East,Patna,3,7807.23,0.03,22719.04,UPI
25070,ORD121575,2025-09-06,CUST10604,New,Backpack,Accessories,West,Pune,2,1663.52,0.03,3227.23,UPI
25071,ORD105390,2025-11-08,CUST12714,Regular,Headphones,Electronics,South,Bengaluru,2,1798.77,0.03,3489.61,Credit Card
25072,ORD100860,2024-01-26,CUST10530,New,Headphones,Electronics,North,Delhi,4,1840.43,0.08,6772.78,Debit Card
25073,ORD115795,2024-02-29,CUST12364,Regular,Desk,Furniture,South,Kochi,4,11139.73,0.03,43222.15,UPI
25074,ORD123654,2024-03-29,CUST11576,Regular,Desk Lamp,Home Appliances,North,Delhi,1,1065.99,0.03,1034.01,UPI

# Level 2 — Data Cleaning

In [7]:
df.isnull().sum()

Order ID          0
Order Date        0
Customer ID       0
Customer Type    35
Product           0
Category          0
Region            0
City             35
Quantity          0
Price Each        0
Discount          0
Sales             0
Payment Mode     30
dtype: int64

* Find Duplicate rows

In [8]:
print(df.duplicated().sum(),'\n')
df.duplicated()

75

0        False
1        False
2        False
3        False
4        False
         ...
25070    False
25071    False
25072    False
25073    False
25074    False
Length: 25075, dtype: bool

In [9]:
df[df.duplicated()]

,Order ID,Order Date,Customer ID,Customer Type,Product,Category,Region,City,Quantity,Price Each,Discount,Sales,Payment Mode
4871,ORD110628,2025-01-21,CUST10567,Regular,T-Shirt,Fashion,South,Hyderabad,2,873.62,0.03,1694.82,Debit Card
5058,ORD114459,2025-09-02,CUST10478,Premium,Backpack,Accessories,North,Chandigarh,4,1539.59,0.10,5542.52,UPI
5659,ORD108544,2024-07-23,CUST10620,Regular,Notebook,Stationery,South,Chennai,4,130.72,0.03,507.19,Credit Card
6891,ORD115868,2025-07-30,CUST10728,Regular,Pen Set,Stationery,North,Chandigarh,1,168.44,0.03,163.39,Debit Card
7327,ORD117597,2025-04-04,CUST11904,Regular,Keyboard,Electronics,East,Kolkata,6,1446.53,0.08,7984.85,Credit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23861,ORD113635,2024-02-24,CUST11868,Premium,T-Shirt,Fashion,East,Bhubaneswar,2,972.15,0.10,1749.87,UPI
24101,ORD113117,2025-06-19,CUST10368,Regular,Water Bottle,Accessories,West,Nashik,1,713.53,0.03,692.12,Credit Card
24601,ORD117058,2025-02-02,CUST12335,Regular,Monitor,Electronics,North,Lucknow,4,10823.49,0.05,41129.26,Credit Card
24688,ORD120326,2025-06-14,CUST12365,Regular,Shoes,Fashion,East,Patna,2,2813.05,0.03,5457.32,UPI
24976,ORD107208,2024-01-18,CUST11752,Regular,T-Shirt,Fashion,North,Chandigarh,6,886.77,0.08,4894.97,UPI

* Drop duplicate rows

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum()

0

* Unique products

In [12]:
df['Product'].unique()

array(['Bookshelf', 'Pen Set', 'Coffee Maker', 'Air Fryer', 'Laptop',
       'Jeans', 'Desk', 'Keyboard', 'Monitor', 'Printer', 'Tablet',
       'Smartphone', 'Backpack', 'T-Shirt', 'Mixer Grinder', 'Mouse',
       'Shoes', 'Blender', 'Headphones', 'Jacket', 'Desk Lamp',
       'Water Bottle', 'Office Chair', 'Notebook'], dtype=object)

In [13]:
df['Customer ID'].unique()

array(['CUST11433', 'CUST11178', 'CUST10146', ..., 'CUST10876',
       'CUST10888', 'CUST11083'], dtype=object)

In [14]:
df['Order Date'].head()

0    2024-10-16
1    2025-08-15
2    2025-09-28
3    2025-09-26
4    2024-03-09
Name: Order Date, dtype: object

In [15]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [16]:
df.head()

,Order ID,Order Date,Customer ID,Customer Type,Product,Category,Region,City,Quantity,Price Each,Discount,Sales,Payment Mode
0,ORD112908,2024-10-16,CUST11433,New,Bookshelf,Furniture,North,Delhi,6,6639.25,0.10,35851.95,Net Banking
1,ORD114592,2025-08-15,CUST11178,Regular,Pen Set,Stationery,West,Aurangabad,2,193.78,0.03,375.93,Debit Card
2,ORD111761,2025-09-28,CUST10146,Regular,Coffee Maker,Home Appliances,West,Pune,5,4122.21,0.05,19580.50,UPI
3,ORD114241,2025-09-26,CUST11112,Regular,Pen Set,Stationery,South,Chennai,2,169.92,0.03,329.64,UPI
4,ORD108748,2024-03-09,CUST11484,Premium,Air Fryer,Home Appliances,North,Delhi,5,6349.53,0.10,28572.88,Credit Card

In [17]:
df['Order Date'].isnull().sum()

0

In [18]:
df.loc[df['Quantity']<0, 'Quantity'].count()

0

In [19]:
df.loc[df['Price Each']<0, 'Price Each'].count()

0

In [20]:
df.shape

(25000, 13)

In [21]:
sales = df['Quantity']*df['Price Each']
df.loc[df['Sales']!=sales-sales*df['Discount'] ,'Sales'].count()

23464

In [22]:
df['Sales'] = sales-sales*df['Discount']

In [23]:
sales = df['Quantity']*df['Price Each']
df.loc[df['Sales']!=sales-sales*df['Discount'] ,'Sales'].count()

0

In [24]:
df.isnull().sum()

Order ID          0
Order Date        0
Customer ID       0
Customer Type    35
Product           0
Category          0
Region            0
City             35
Quantity          0
Price Each        0
Discount          0
Sales             0
Payment Mode     30
dtype: int64

In [25]:
df['Customer Type'] = np.where(df['Customer Type'].isnull(), 'Regular', df['Customer Type'])
# Another method
#df['Customer Type'].fillna('Regular' , inplace = True)

In [26]:
df.isnull().sum()

Order ID          0
Order Date        0
Customer ID       0
Customer Type     0
Product           0
Category          0
Region            0
City             35
Quantity          0
Price Each        0
Discount          0
Sales             0
Payment Mode     30
dtype: int64

In [27]:
df.dropna(axis=0 , inplace=True)

In [28]:
df.shape

(24935, 13)

# Numpy operations

In [29]:
print("Mean :",np.mean(df['Sales']))
print("Median :",np.median(df['Sales']))
print("Max :",np.max(df['Sales']))
print("Min :",np.min(df['Sales']))
print("std :",np.std(df['Sales']))

Mean : 23379.18542711851
Median : 8419.0665
Max : 550233.232
Min : 98.7096
std : 44223.2216762846

# Filtering

In [30]:
df.loc[df['Sales']>1000 , ('Sales','Product')]

             Sales       Product
0       35851.9500     Bookshelf
2       19580.4975  Coffee Maker
4       28572.8850     Air Fryer
5      319605.7368        Laptop
6        1807.5659         Jeans
...            ...           ...
25070    3227.2288      Backpack
25071    3489.6138    Headphones
25072    6772.7824    Headphones
25073   43222.1524          Desk
25074    1034.0103     Desk Lamp

[22406 rows x 2 columns]

In [32]:
df.loc[(df['Quantity']>5) & (df['Sales']>500), 'Sales']

0         35851.9500
5        319605.7368
26       102121.8768
30        61629.6240
31        18157.1568
            ...
25045     10733.0880
25047     70430.2228
25057     36184.7040
25063     27715.7520
25067     39144.2744
Name: Sales, Length: 4477, dtype: float64

In [ ]:
df.loc[df['City']== 'Mumbai','Sales']

20       36259.4148
22       11396.4136
24        2352.4560
27        2709.0000
41       37766.0091
            ...
24968     3478.8620
24969     1427.8012
25001    61982.9640
25020    46105.3416
25035     6566.3568
Name: Sales, Length: 1553, dtype: float64

In [33]:
df.loc[df['Order Date'].dt.year ==  2025]

,Order ID,Order Date,Customer ID,Customer Type,Product,Category,Region,City,Quantity,Price Each,Discount,Sales,Payment Mode
1,ORD114592,2025-08-15,CUST11178,Regular,Pen Set,Stationery,West,Aurangabad,2,193.78,0.03,375.9332,Debit Card
2,ORD111761,2025-09-28,CUST10146,Regular,Coffee Maker,Home Appliances,West,Pune,5,4122.21,0.05,19580.4975,UPI
3,ORD114241,2025-09-26,CUST11112,Regular,Pen Set,Stationery,South,Chennai,2,169.92,0.03,329.6448,UPI
5,ORD112116,2025-10-07,CUST11540,Regular,Laptop,Electronics,North,Delhi,6,57899.59,0.08,319605.7368,UPI
6,ORD101427,2025-01-25,CUST10382,Regular,Jeans,Fashion,East,Bhubaneswar,1,1863.47,0.03,1807.5659,Credit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25065,ORD116850,2025-12-01,CUST10473,Premium,Coffee Maker,Home Appliances,North,Delhi,3,4064.00,0.10,10972.8000,Credit Card
25066,ORD106265,2025-12-05,CUST10589,Regular,Mouse,Electronics,West,Aurangabad,3,689.46,0.03,2006.3286,Net Banking
25068,ORD111284,2025-11-24,CUST12109,Premium,Blender,Home Appliances,South,Kochi,4,2792.39,0.10,10052.6040,UPI
25070,ORD121575,2025-09-06,CUST10604,New,Backpack,Accessories,West,Pune,2,1663.52,0.03,3227.2288,UPI
25071,ORD105390,2025-11-08,CUST12714,Regular,Headphones,Electronics,South,Bengaluru,2,1798.77,0.03,3489.6138,Credit Card

In [ ]:
df.nlargest(20,'Sales')

# df.sort_values(by='Sales, ascending = False).head(20)

,Order ID,Order Date,Customer ID,Customer Type,Product,Category,Region,City,Quantity,Price Each,Discount,Sales,Payment Mode
23995,ORD107041,2025-04-03,CUST11317,Regular,Laptop,Electronics,East,Patna,10,59807.96,0.08,550233.2320,Net Banking
11779,ORD116800,2025-03-30,CUST10515,New,Laptop,Electronics,South,Kochi,10,57918.41,0.08,532849.3720,UPI
18779,ORD102721,2024-06-10,CUST12363,Regular,Laptop,Electronics,South,Kochi,10,58690.49,0.10,528214.4100,UPI
12604,ORD115948,2024-06-04,CUST12616,New,Laptop,Electronics,West,Mumbai,10,56884.71,0.08,523339.3320,Debit Card
16508,ORD102401,2024-09-09,CUST11073,Regular,Laptop,Electronics,West,Mumbai,10,56653.56,0.08,521212.7520,Net Banking
18698,ORD119062,2025-02-17,CUST12485,New,Laptop,Electronics,West,Pune,10,56034.41,0.08,515516.5720,UPI
818,ORD110806,2025-02-28,CUST11832,Regular,Laptop,Electronics,South,Bengaluru,10,56841.68,0.10,511575.1200,Net Banking
8927,ORD116398,2025-04-12,CUST12529,Regular,Laptop,Electronics,East,Kolkata,10,56283.40,0.10,506550.6000,Net Banking
13155,ORD111842,2025-11-15,CUST12117,Regular,Laptop,Electronics,West,Mumbai,10,54220.99,0.08,498833.1080,Cash
1666,ORD107712,2025-12-10,CUST12621,Premium,Laptop,Electronics,East,Bhubaneswar,10,55271.37,0.10,497442.3300,Cash
17651,ORD110931,2025-09-18,CUST11308,Regular,Laptop,Electronics,North,Jaipur,10,57094.12,0.13,496718.8440,Net Banking
19196,ORD108531,2025-09-24,CUST10091,Premium,Laptop,Electronics,South,Hyderabad,10,54396.94,0.10,489572.4600,UPI
18180,ORD106617,2024-12-26,CUST12867,Premium,Laptop,Electronics,South,Hyderabad,10,54333.09,0.10,488997.8100,Debit Card
277,ORD110163,2024-03-23,CUST12963,Regular,Laptop,Electronics,South,Hyderabad,10,51314.37,0.08,472092.2040,UPI
22293,ORD109518,2025-08-07,CUST10712,New,Laptop,Electronics,North,Chandigarh,10,51255.28,0.08,471548.5760,Cash
9986,ORD124083,2025-09-22,CUST12455,Regular,Laptop,Electronics,West,Mumbai,10,50686.21,0.08,466313.1320,Cash
23451,ORD123586,2024-07-02,CUST11241,Regular,Laptop,Electronics,North,Jaipur,8,60178.57,0.08,442914.2752,Cash
21167,ORD124689,2025-01-08,CUST10381,Regular,Laptop,Electronics,South,Hyderabad,8,60059.08,0.08,442034.8288,Net Banking
448,ORD124706,2025-04-25,CUST10123,Regular,Laptop,Electronics,East,Kolkata,8,60058.63,0.08,442031.5168,UPI
11771,ORD100633,2024-03-31,CUST11787,Regular,Laptop,Electronics,West,Mumbai,8,59814.50,0.08,440234.7200,Cash

* Sales by product

In [43]:
df.groupby('Product')['Sales'].sum().nlargest(1)

Product
Laptop    1.713466e+08
Name: Sales, dtype: float64

* Sales by category

In [62]:
df.groupby('Category')['Sales'].sum()

Category
Accessories        7.590030e+06
Electronics        3.874068e+08
Fashion            2.965326e+07
Furniture          9.287764e+07
Home Appliances    6.435997e+07
Stationery         1.072298e+06
Name: Sales, dtype: float64

In [63]:
print("Best Performing")
best = df.groupby('Category')['Sales'].sum().nlargest(1)
best

Best Performing

Category
Electronics    3.874068e+08
Name: Sales, dtype: float64

# Sales by Region

In [61]:
df.groupby('Region')['Sales'].sum()

Region
Central    3.365818e+07
East       1.148183e+08
North      1.394801e+08
South      1.491949e+08
West       1.458085e+08
Name: Sales, dtype: float64

* Best Region

In [ ]:
df.groupby('Region')['Sales'].sales().nlargest(1)

Region
South    6324
Name: Sales, dtype: int64

* Quantity Sold by product

In [64]:
df.groupby('Product')['Quantity'].sum()

Product
Air Fryer        3578
Backpack         3561
Blender          3715
Bookshelf        3744
Coffee Maker     3843
Desk             3597
Desk Lamp        3650
Headphones       3565
Jacket           3509
Jeans            3580
Keyboard         3762
Laptop           3340
Mixer Grinder    3819
Monitor          3622
Mouse            3770
Notebook         3846
Office Chair     3771
Pen Set          3818
Printer          3624
Shoes            3510
Smartphone       3448
T-Shirt          3527
Tablet           3539
Water Bottle     3750
Name: Quantity, dtype: int64

* Category Average

In [65]:

df.groupby('Category')['Price Each'].mean()

Category
Accessories         1119.373912
Electronics        14628.577431
Fashion             2261.257597
Furniture           9025.276046
Home Appliances     3722.082618
Stationery           150.564438
Name: Price Each, dtype: float64

# Sorting

* Sort products by total sales:

In [66]:
sort_product = df.groupby('Product')['Sales'].sum().sort_values(ascending=False)

* Top 10 product by revenue.

In [67]:
sort_product.head(10)

Product
Laptop          1.713466e+08
Smartphone      7.079598e+07
Tablet          5.947118e+07
Monitor         4.040295e+07
Desk            4.034796e+07
Printer         3.204889e+07
Office Chair    2.990718e+07
Bookshelf       2.262250e+07
Air Fryer       2.170560e+07
Coffee Maker    1.504021e+07
Name: Sales, dtype: float64

* Bottom 10 product

In [68]:
sort_product.tail(10)

Product
Jeans           6.018419e+06
Headphones      5.979879e+06
Backpack        5.316202e+06
Keyboard        4.903219e+06
Desk Lamp       3.743120e+06
T-Shirt         2.966062e+06
Mouse           2.458104e+06
Water Bottle    2.273829e+06
Pen Set         6.422970e+05
Notebook        4.300012e+05
Name: Sales, dtype: float64

* Find the top 10 cities by sales.

In [69]:
df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(10)

City
Bhubaneswar    4.182862e+07
Mumbai         4.017183e+07
Kochi          3.812902e+07
Patna          3.758107e+07
Bengaluru      3.741146e+07
Jaipur         3.736468e+07
Hyderabad      3.718405e+07
Chennai        3.647037e+07
Pune           3.632999e+07
Lucknow        3.547066e+07
Name: Sales, dtype: float64

# Level 7 — Time-Series Analysis

* Add Column

In [70]:
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Month Name'] = df['Order Date'].dt.month_name()

In [72]:
df.head()

,Order ID,Order Date,Customer ID,Customer Type,Product,Category,Region,City,Quantity,Price Each,Discount,Sales,Payment Mode,Year,Month,Month Name
0,ORD112908,2024-10-16,CUST11433,New,Bookshelf,Furniture,North,Delhi,6,6639.25,0.10,35851.9500,Net Banking,2024,10,October
1,ORD114592,2025-08-15,CUST11178,Regular,Pen Set,Stationery,West,Aurangabad,2,193.78,0.03,375.9332,Debit Card,2025,8,August
2,ORD111761,2025-09-28,CUST10146,Regular,Coffee Maker,Home Appliances,West,Pune,5,4122.21,0.05,19580.4975,UPI,2025,9,September
3,ORD114241,2025-09-26,CUST11112,Regular,Pen Set,Stationery,South,Chennai,2,169.92,0.03,329.6448,UPI,2025,9,September
4,ORD108748,2024-03-09,CUST11484,Premium,Air Fryer,Home Appliances,North,Delhi,5,6349.53,0.10,28572.8850,Credit Card,2024,3,March

* Total sales by year

In [73]:
df.groupby('Year')['Sales'].sum()

Year
2024    2.890717e+08
2025    2.938882e+08
Name: Sales, dtype: float64

* Total sales by month

In [77]:
sales_per_month = df.groupby('Month Name')['Sales'].sum()
sales_per_month

Month Name
April        4.641313e+07
August       4.895658e+07
December     4.967679e+07
February     4.445160e+07
January      5.308964e+07
July         5.187831e+07
June         4.965147e+07
March        4.760665e+07
May          4.883060e+07
November     4.473376e+07
October      4.792621e+07
September    4.974524e+07
Name: Sales, dtype: float64

* Which Month has highest sales

In [78]:
sales_per_month.sort_values(ascending=False).nlargest(1)

Month Name
January    5.308964e+07
Name: Sales, dtype: float64

* Which Month has lowest sales.

In [79]:
sales_per_month.sort_values(ascending=True).nlargest(1)

Month Name
January    5.308964e+07
Name: Sales, dtype: float64

* Calculate monthly average sales

In [80]:
df.groupby('Month Name')['Sales'].mean()

Month Name
April        22563.503524
August       22560.635643
December     24483.386641
February     23860.225159
January      24727.361224
July         23885.042570
June         24137.807579
March        22183.902515
May          23692.673310
November     22112.586534
October      22270.543531
September    24171.641225
Name: Sales, dtype: float64

* Find the best-performing year.

In [82]:
df.groupby('Year')['Sales'].sum().sort_values(ascending=False).nlargest(1)

Year
2025    2.938882e+08
Name: Sales, dtype: float64

# Level 8

In [ ]:
pd.pivot_table(
    data=df,
    values='Sales',
    index='Product',
    columns='Region',
    aggfunc='sum'
)

In [ ]:
#  Same but if diffrent form
df.groupby(['Region','Product'])['Sales'].sum()

* Region × Category

In [99]:
pd.pivot_table(
    data = df,
    values='Sales',
    index='Region',
    columns='Category',
    aggfunc='sum'
)

Category,Accessories,Electronics,Fashion,Furniture,Home Appliances,Stationery
Region,,,,,,
Central,4.843967e+05,2.082745e+07,1.739507e+06,6.253780e+06,4.293023e+06,60024.4247
East,1.340119e+06,7.764113e+07,5.462962e+06,1.792998e+07,1.225756e+07,186539.5736
North,2.084378e+06,9.206293e+07,6.857490e+06,2.250037e+07,1.568879e+07,286117.7137
South,1.971546e+06,1.009777e+08,7.664414e+06,2.189243e+07,1.642342e+07,265387.4394
West,1.709590e+06,9.589757e+07,7.928889e+06,2.430108e+07,1.569717e+07,274229.0455

* Month × Category

In [98]:
pd.pivot_table(
    data=df,
    values='Sales',
    index='Month Name',
    columns='Category',
    aggfunc = 'sum'
    )

Category,Accessories,Electronics,Fashion,Furniture,Home Appliances,Stationery
Month Name,,,,,,
April,716625.8702,3.084311e+07,2.192443e+06,6.820398e+06,5.746656e+06,93891.8421
August,709324.1698,3.181006e+07,2.726806e+06,8.079761e+06,5.549251e+06,81380.8451
December,643516.4807,3.371390e+07,2.228846e+06,7.559362e+06,5.452532e+06,78638.5088
February,566435.0275,2.939676e+07,2.242684e+06,8.055220e+06,4.101906e+06,88590.5724
January,663900.9774,3.615546e+07,2.473829e+06,7.793553e+06,5.905442e+06,97463.9192
July,599786.7229,3.427219e+07,2.468694e+06,8.750571e+06,5.714729e+06,72339.6425
June,648780.8496,3.477335e+07,2.600542e+06,6.625421e+06,4.908555e+06,94820.2100
March,668964.5493,3.040396e+07,2.914782e+06,7.755786e+06,5.765930e+06,97233.0777
May,595847.8600,3.294097e+07,2.368199e+06,7.473748e+06,5.361764e+06,90074.9625
November,649543.1521,2.901783e+07,2.174438e+06,7.745264e+06,5.052092e+06,94593.9053
October,602779.3445,3.083845e+07,2.645452e+06,8.145115e+06,5.602303e+06,92106.1875
September,524525.4403,3.324076e+07,2.616546e+06,8.073437e+06,5.198805e+06,91164.5238

* Region × Payment Mode

In [100]:
pd.pivot_table(
    data=df,
    values='Quantity',
    index='Region',
    columns='Payment Mode',
    aggfunc='sum'
)

Payment Mode  Cash  Credit Card  Debit Card  Net Banking   UPI
Region
Central        394         1182         924          735  2190
East          1474         4070        2670         1907  6271
North         1867         4917        3703         2568  8715
South         1694         5397        3732         2527  8832
West          1694         4947        3687         2614  8777